Repository somatech1/mikros, pull requests merged in 2024-04, with the labels that each got.

#9 feat: Add new function `FromGRPCStatus` to convert grpc status to Mik…
  components/grpc/grpc.go
  internal/components/errors/errors.go
Labels: area/backend, kind/feature, state/approved

#10 feat: Add panic recovery feature to HTTP server
  apis/http_panic_recovery/http_panic_recovery.go
  components/definition/definition.go
  components/options/features.go
  internal/services/http/http.go
Labels: area/backend, kind/feature, state/approved

#12 fix: only initialize annotated gRPC clients
  service.go
Labels: area/backend, kind/bug

#13 feat: improve env public API
  env.go
Labels: area/backend, kind/feature

#14 fix: dependabot issues
  go.mod
  go.sum
Labels: area/backend, kind/bug
